const $ = s => document.querySelector(s);
const input=$('#fileInput'), drop=$('#dropZone'), list=$('#imageList'), canvas=$('#canvas'), ctx=canvas.getContext('2d');
const items=[]; let running=false;
const modeLabels={long:'긴 축 길이 (px)',short:'짧은 축 길이 (px)',width:'X축 길이 (px)',height:'Y축 길이 (px)',percent:'크기 비율 (%)'};
const extFor={"image/jpeg":"jpg","image/png":"png","image/webp":"webp"};
function updateUI(){ const n=items.length; $('#count').textContent=n; $('#emptyState').hidden=!!n; $('#resizeBtn').disabled=!n||running; $('#zipBtn').disabled=!items.some(i=>i.output); $('#clearBtn').disabled=!n; $('#summary').textContent=n?'· 변환 전':''; }
function baseName(name){return name.replace(/\.[^.]+$/,'');}
function addFiles(files){ [...files].filter(f=>f.type.startsWith('image/')).forEach(file=>{const url=URL.createObjectURL(file), img=new Image(); const item={file,url,img,output:null}; img.onload=()=>{item.w=img.naturalWidth;item.h=img.naturalHeight; renderItem(item);}; img.src=url;items.push(item);}); updateUI(); }
function renderItem(item){ let card=item.card;if(!card){card=$('#cardTemplate').content.firstElementChild.cloneNode(true);item.card=card;card.querySelector('img').src=item.url;card.querySelector('.file-name').textContent=item.file.name;card.querySelector('.remove').onclick=()=>remove(item);card.querySelector('.download').onclick=()=>downloadItem(item);list.append(card)} const d=card.querySelector('.dimensions');d.textContent=`원본 ${item.w} × ${item.h}px${item.outW?` → 결과 ${item.outW} × ${item.outH}px`:''}`; }
function remove(item){ if(item.output)URL.revokeObjectURL(item.output.url);URL.revokeObjectURL(item.url);items.splice(items.indexOf(item),1);item.card.remove();updateUI(); }
function dimensions(w,h){const m=$('#mode').value,v=Math.max(1,Number($('#sizeValue').value)||1);let scale;if(m==='long')scale=v/Math.max(w,h);if(m==='short')scale=v/Math.min(w,h);if(m==='width')scale=v/w;if(m==='height')scale=v/h;if(m==='percent')scale=v/100;return [Math.max(1,Math.round(w*scale)),Math.max(1,Math.round(h*scale))];}
function outType(file){const f=$('#format').value;return f==='original'&&['image/jpeg','image/png','image/webp'].includes(file.type)?file.type:(f==='original'?'image/png':f)}
async function resizeAll(){if(running)return;running=true;updateUI();const btn=$('#resizeBtn');btn.textContent='변환 중…';for(const item of items){const [w,h]=dimensions(item.w,item.h);canvas.width=w;canvas.height=h;ctx.clearRect(0,0,w,h);ctx.drawImage(item.img,0,0,w,h);const type=outType(item.file),q=Number($('#quality').value)/100;const blob=await new Promise(r=>canvas.toBlob(r,type,q));if(item.output)URL.revokeObjectURL(item.output.url);item.output={blob,type,name:`${baseName(item.file.name)}_${w}x${h}.${extFor[type]}` ,url:URL.createObjectURL(blob)};item.outW=w;item.outH=h;renderItem(item);const s=item.card.querySelector('.status');s.textContent='변환 완료';s.classList.add('done');item.card.querySelector('.download').disabled=false;}running=false;btn.textContent='리사이징 실행';$('#summary').textContent=`· ${items.length}개 변환 완료`;updateUI();}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}function downloadItem(i){download(i.output.blob,i.output.name)}
// ZIP (store mode): browser-native Blob only, no network or external library required.
const crcTable=(()=>{const t=[];for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=c&1?0xedb88320^(c>>>1):c>>>1;t[n]=c>>>0}return t})();
function crc32(bytes){let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0}function u16(n){return new Uint8Array([n&255,n>>>8&255])}function u32(n){return new Uint8Array([n&255,n>>>8&255,n>>>16&255,n>>>24&255])}function join(a){let l=a.reduce((s,x)=>s+x.length,0),o=new Uint8Array(l),p=0;for(const x of a){o.set(x,p);p+=x.length}return o}
async function downloadZip(){const ready=items.filter(i=>i.output);if(!ready)return;const files=await Promise.all(ready.map(async i=>({name:new TextEncoder().encode(i.output.name),data:new Uint8Array(await i.output.blob.arrayBuffer())})));let offset=0;const locals=[],centrals=[];for(const f of files){const crc=crc32(f.data),size=f.data.length;locals.push(join([u32(0x04034b50),u16(20),u16(0x800),u16(0),u16(0),u16(0),u32(crc),u32(size),u32(size),u16(f.name.length),u16(0),f.name,f.data]));centrals.push(join([u32(0x02014b50),u16(20),u16(20),u16(0x800),u16(0),u16(0),u16(0),u32(crc),u32(size),u32(size),u16(f.name.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),f.name]));offset+=locals.at(-1).length}const central=join(centrals),zip=join([...locals,central,u32(0x06054b50),u16(0),u16(0),u16(files.length),u16(files.length),u32(central.length),u32(offset),u16(0)]);download(new Blob([zip],{type:'application/zip'}),'resized-images.zip')}
input.onchange=e=>{addFiles(e.target.files);input.value=''};['dragenter','dragover'].forEach(e=>drop.addEventListener(e,x=>{x.preventDefault();drop.classList.add('dragover')}));['dragleave','drop'].forEach(e=>drop.addEventListener(e,x=>{x.preventDefault();drop.classList.remove('dragover')}));drop.addEventListener('drop',e=>addFiles(e.dataTransfer.files));$('#mode').onchange=()=>{$('#sizeLabel').textContent=modeLabels[$('#mode').value];$('#settingHint').textContent=$('#mode').value==='percent'?'예: 50은 원본의 절반, 200은 원본의 두 배입니다.':'가로·세로 비율은 항상 유지됩니다.'};$('#quality').oninput=()=>$('#qualityValue').textContent=$('#quality').value;$('#resizeBtn').onclick=resizeAll;$('#zipBtn').onclick=downloadZip;$('#clearBtn').onclick=()=>{[...items].forEach(remove)};updateUI();
